-- Retired security-sensitive one-off password reset.
-- Do not store real user passwords in migrations. Use the Supabase dashboard
-- or an operational runbook with temporary credentials when a reset is needed.
